/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * pantry API
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 */

export interface PantryItem {
  id?: number;
  name?: string;
  description?: string;
  quantity?: number;
  quantityUnitType?: string;
}
