compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0062
    level: discard
  - code: YN0002
    level: info

nodeLinker: node-modules

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-3.2.2.cjs
