compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0062
    level: discard
  - code: YN0002
    level: info

nodeLinker: node-modules

pnpEnableEsmLoader: false

packageExtensions:
  "flowbite-react@*":
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-3.8.7.cjs
