name: Pantry PR

on:
  pull_request:
    branches: [ "trunk" ]

jobs:
  react:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'src/main/webui'

    strategy:
      matrix:
        node-version: [ '16.x', '18.x' ]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Node.js packages
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Run linter
      run: yarn lint
    - name: Run test build
      run: yarn next build

  quarkus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Run maven test
      run: mvn test
