name: Pantry PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  react:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './src/main/webui'

    strategy:
      matrix:
        node-version: [ '18.x', '20.x', '22.x' ]

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: './src/main/webui/yarn.lock'
    - name: Install Node.js packages
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Run linter
      run: yarn lint
    - name: Run test build
      run: yarn build

  quarkus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Use Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build & Install
      run: mvn -B install -D skipTests --no-transfer-progress
    - name: Ensure browsers are installed
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
    - name: Run maven test
      run: mvn test
